wxpay:
  appid: wx8397f8696b538317
  mchid: 1473426802
  key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  notifyUrl: http://portal-hongbaoyu-java.itsyduck.net/payment/api/nofify
  domain: api.mch.weixin.qq.com